# Primary font
# font_family      Consolas
# bold_font        Consolas Bold
# italic_font      Consolas Italic
# bold_italic_font Consolas Bold Italic
# font_size 12.0
#
# # Fallback font for icons/symbols
# symbol_map U+E000-U+F8FF FiraCode Nerd Font
# symbol_map U+F0000-U+FFFFF FiraCode Nerd Font
# symbol_map U+20000-U+2FFFF FiraCode Nerd Font

font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font Bold
italic_font      FiraCode Nerd Font Italic
bold_italic_font FiraCode Nerd Font Bold Italic
font_size 12.0

cursor_shape block

background_opacity 0.90
dynamic_background_opacity yes
enable_audio_bell no
scrollback_lines 500
background_blur 0
repaint_delay 10
input_delay 5   
